# Generated by Django 3.0.5 on 2021-09-03 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_hisab_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='address',
            field=models.CharField(default='model town,ratia', max_length=500),
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.IntegerField(default='125051'),
        ),
        migrations.AddField(
            model_name='customer',
            name='re_enter_password',
            field=models.CharField(default='****', max_length=500),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.IntegerField(default='8928'),
        ),
    ]
